# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=26)),
                ('user_dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('user_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=26)),
                ('has_Colleges', models.BooleanField()),
                ('has_Libraries', models.BooleanField()),
                ('has_Industries', models.BooleanField()),
                ('has_Hotels', models.BooleanField()),
                ('has_Parks', models.BooleanField()),
                ('has_Zoos', models.BooleanField()),
                ('has_Museums', models.BooleanField()),
                ('has_Restaurants', models.BooleanField()),
                ('has_Malls', models.BooleanField()),
            ],
        ),
    ]
