# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Colleges')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('library_id', models.AutoField(primary_key=True, serialize=False)),
                ('library_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Malls',
            fields=[
                ('mall_id', models.AutoField(primary_key=True, serialize=False)),
                ('mall_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Museums',
            fields=[
                ('museum_id', models.AutoField(primary_key=True, serialize=False)),
                ('museum_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('park_id', models.AutoField(primary_key=True, serialize=False)),
                ('park_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('weather', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zoos',
            fields=[
                ('zoo_id', models.AutoField(primary_key=True, serialize=False)),
                ('zoo_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Colleges',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Hotels',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Industries',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Libraries',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Malls',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Museums',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Parks',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Restaurants',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Zoos',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='type_name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_city',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_firstname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_lastname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertype',
            name='type_desc',
            field=models.CharField(default='type_desc', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertype',
            name='type_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='cities',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Weather'),
        ),
    ]
