# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0002_auto_20171101_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='home_city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
