# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0003_auto_20171105_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_city',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
