# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='hotel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='malls',
            old_name='mall_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='museums',
            old_name='museum_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parks',
            old_name='park_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='restaurant_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='zoos',
            old_name='zoo_name',
            new_name='name',
        ),
    ]
