# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.IntegerField(default=1)),
                ('college_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Colleges')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField(default=1)),
                ('hotel_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_id', models.IntegerField(default=1)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Colleges')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=100)),
                ('Industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Industries')),
            ],
        ),
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.IntegerField(default=1)),
                ('library_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Malls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall_id', models.IntegerField(default=1)),
                ('mall_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Museums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_id', models.IntegerField(default=1)),
                ('museum_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_id', models.IntegerField(default=1)),
                ('park_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(default=1)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_id', models.IntegerField(default=1)),
                ('weather', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zoos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoo_id', models.IntegerField(default=1)),
                ('zoo_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Cities')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Colleges',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Hotels',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Industries',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Libraries',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Malls',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Museums',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Parks',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Restaurants',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='has_Zoos',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='type_name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='home_city',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usertype',
            name='type_desc',
            field=models.CharField(default='type_desc', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertype',
            name='type_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='cities',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycity.Weather'),
        ),
    ]
