# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0004_remove_industrytype_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='id',
        ),
        migrations.RemoveField(
            model_name='colleges',
            name='id',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='id',
        ),
        migrations.RemoveField(
            model_name='industries',
            name='id',
        ),
        migrations.RemoveField(
            model_name='industrytype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='libraries',
            name='id',
        ),
        migrations.RemoveField(
            model_name='malls',
            name='id',
        ),
        migrations.RemoveField(
            model_name='museums',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='id',
        ),
        migrations.RemoveField(
            model_name='zoos',
            name='id',
        ),
        migrations.AlterField(
            model_name='cities',
            name='city_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='college_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='department_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industries',
            name='industry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industrytype',
            name='type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='library_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='malls',
            name='mall_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='museums',
            name='museum_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parks',
            name='park_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='restaurant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zoos',
            name='zoo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
